
language: node_js
node_js:
  - "4.2.1"
script:
  - npm test
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install history@1.13.x